name = "Supergrassi"
uuid = "524c9cd3-385d-434e-bae6-611159fb61cc"
authors = ["Tuomas Koskela <t.koskela@ucl.ac.uk> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
