categories:
  - Agriculture
  - Forestry
  - Fishing
  - Mining
  - "Manufacturing: food"
  - "Manufacturing: textiles"
  - "Manufacturing: wood"
  - "Manufacturing: paper"
  - Printing
  - "Manufacturing: coke"
  - "Manufacturing: chemicals"
  - "Manufacturing: pharmaceuticals"
  - "Manufacturing: rubber"
  - "Manufacturing: minerals"
  - "Manufacturing: metals"
  - "Manufacturing: fabricated metals"
  - "Manufacturing: computers"
  - "Manufacturing: electrical"
  - "Manufacturing: machinery"
  - "Manufacturing: motor vehicles"
  - "Manufacturing: other transport"
  - "Manufacturing: other"
  - "Machinery repair"
  - Electricity
  - Water
  - Sewerage
  - Construction
  - "Wholesale/retail: motor vehicles"
  - "Wholesale: other"
  - "Retail: other"
  - "Land transport"
  - "Water transport"
  - "Air transport"
  - Warehousing
  - Postal
  - "Accommodation/food services"
  - Publishing
  - Film
  - Telecoms
  - Programming
  - Financial
  - Insurance
  - "Other financial/insurance services"
  - "Real estate"
  - "Imputed rents"
  - "Legal/accounting"
  - Architecture
  - "R&D"
  - Advertising
  - "Other professional"
  - "Rental services"
  - "Employment services"
  - Travel
  - "Other office services"
  - "Public administration"
  - Education
  - Health
  - "Social work"
  - Arts
  - Sports
  - "Membership organizations"
  - "Household goods repair"
  - "Other personal services"
  - "Household employers"
